<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE CLIMATE [
 <!ELEMENT CLIMATE (DATA*)>
 <!ELEMENT DATA (MONTH,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,YEAR)>
 <!ELEMENT MONTH (#PCDATA)>
 <!ELEMENT JAN (#PCDATA)>
 <!ELEMENT FEB (#PCDATA)>
 <!ELEMENT MAR (#PCDATA)>
 <!ELEMENT APR (#PCDATA)>
 <!ELEMENT MAY (#PCDATA)>
 <!ELEMENT JUN (#PCDATA)>
 <!ELEMENT JUL (#PCDATA)>
 <!ELEMENT AUG (#PCDATA)>
 <!ELEMENT SEP (#PCDATA)>
 <!ELEMENT OCT (#PCDATA)>
 <!ELEMENT NOV (#PCDATA)>
 <!ELEMENT DEC (#PCDATA)>
 <!ELEMENT YEAR (#PCDATA)>
]>

<CLIMATE>

<DATA>
<MONTH>Month</MONTH>
<JAN>Jan</JAN>
<FEB>Feb</FEB>
<MAR>Mar</MAR>
<APR>Apr</APR>
<MAY>May</MAY>
<JUN>Jun</JUN>
<JUL>Jul</JUL>
<AUG>Aug</AUG>
<SEP>Sep</SEP>
<OCT>Oct</OCT>
<NOV>Nov</NOV>
<DEC>Dec</DEC>
<YEAR>Year</YEAR>
</DATA>

<DATA>
<MONTH>Record high *C</MONTH>
<JAN>33.0</JAN>
<FEB>36.7</FEB>
<MAR>35.2</MAR>
<APR>36.0</APR>
<MAY>36.4</MAY>
<JUN>40.0</JUN>
<JUL>40.0</JUL>
<AUG>34.9</AUG>
<SEP>35.0</SEP>
<OCT>37.0</OCT>
<NOV>36.9</NOV>
<DEC>33.2</DEC>
<YEAR>40.0</YEAR>
</DATA>

<DATA>
<MONTH>Average high *C</MONTH>
<JAN>26.1</JAN>
<FEB>26.2</FEB>
<MAR>27.4</MAR>
<APR>27.7</APR>
<MAY>28.9</MAY>
<JUN>29.4</JUN>
<JUL>29.7</JUL>
<AUG>30.6</AUG>
<SEP>30.5</SEP>
<OCT>30.7</OCT>
<NOV>29.4</NOV>
<DEC>27.6</DEC>
<YEAR>28.7</YEAR>
</DATA>
<DATA>
<MONTH>Daily mean *C</MONTH>
<JAN>22</JAN>
<FEB>22</FEB>
<MAR>22</MAR>
<APR>23</APR>
<MAY>24</MAY>
<JUN>24</JUN>
<JUL>25</JUL>
<AUG>26</AUG>
<SEP>26</SEP>
<OCT>26</OCT>
<NOV>25</NOV>
<DEC>23</DEC>
<YEAR>24</YEAR>
</DATA>
<DATA>
<MONTH>Average low *C</MONTH>
<JAN>19.7</JAN>
<FEB>19.2</FEB>
<MAR>19.4</MAR>
<APR>20.2</APR>
<MAY>21.1</MAY>
<JUN>21.9</JUN>
<JUL>23.3</JUL>
<AUG>24.3</AUG>
<SEP>24.4</SEP>
<OCT>24.1</OCT>
<NOV>22.8</NOV>
<DEC>21.4</DEC>
<YEAR>21.8</YEAR>
</DATA>

<DATA>
<MONTH>Record low *C</MONTH>
<JAN>10.0</JAN>
<FEB>10.2</FEB>
<MAR>10.0</MAR>
<APR>14.0</APR>
<MAY>10.7</MAY>
<JUN>14.1</JUN>
<JUL>11.0</JUL>
<AUG>16.0</AUG>
<SEP>18.0</SEP>
<OCT>19.4</OCT>
<NOV>16.4</NOV>
<DEC>16.0</DEC>
<YEAR>10.0</YEAR>
</DATA>
<DATA>
<MONTH>Average relative humidity (%)</MONTH>
<JAN>61</JAN>
<FEB>58</FEB>
<MAR>57</MAR>
<APR>56</APR>
<MAY>57</MAY>
<JUN>61</JUN>
<JUL>67</JUL>
<AUG>50</AUG>
<SEP>47</SEP>
<OCT>67</OCT>
<NOV>64</NOV>
<DEC>63</DEC>
<YEAR>59</YEAR>
</DATA>

</CLIMATE>